---
title: "fifa champs"
author: "jrwalker"
date: "July 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
```


```{r}
champs <- data_frame(country  = c("USA", "Norway", "USA", "Germany", "Germany", "Japan", "USA"), iso = c("US", "NO", "US", "DE", "DE", "JP", "US"), yr = c(1991, 1995, 1999, 2003, 2007, 2011, 2015)) 
ch_count <- champs %>%
  group_by(country) %>%
  summarise(wins = n(),
            recent = max(yr)) %>%
  ungroup() %>%
  rename(region = country) %>%
  arrange(desc(wins))
map.world <- map_data('world') %>% 
  left_join(ch_count, by = "region") %>%
  mutate(wins = ifelse(is.na(wins), 0, wins),
         wins = factor(wins))
```

```{r}
ggplot(data=map.world, aes(x=long, y=lat)) +
  geom_polygon(colour = "black", aes(fill = wins, group = group)) +
  coord_cartesian(ylim=c(-55,68)) +
  scale_fill_manual(values = c("#d9d9d9", "#99d8c9", "#41ae76", "#00441b"), aesthetics = "fill") +
  theme_void() + theme(legend.position = "bottom") +
  annotate("text", label = "FIFA women's champsionships by country", x = -20, y = 70, size = 8, colour = "#00441b")
  
```

