---
title: "fifa champs"
author: "jrwalker"
date: "July 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
```


```{r}
champs <- data_frame(country  = c("Uruguay", "Italy", "Italy", "Uruguay", "Germany", "Brazil", "Brazil", "UK", "Brazil", "Germany", "Argentina", "Italy", "Argentina", "Germany", "Brazil", "France", "Brazil", "Italy", "Spain", "Germany", "France"), iso = c("UY", "IT", "IT", "UY", "DE", "BR", "BR", "UK", "BR", "DE", "AR", "IT", "AR", "DE", "BR", "FR", "BR", "IT", "ES", "DE", "FR"), yr = c(1930, 1934, 1938, 1950, 1954, 1958, 1962, 1966, 1970, 1974, 1978, 1982, 1986, 1990, 1994, 1998, 2002, 2006, 2010, 2014, 2018)) 
ch_count <- champs %>%
  group_by(country) %>%
  summarise(wins = n(),
            recent = max(yr)) %>%
  ungroup() %>%
  rename(region = country) %>%
  arrange(desc(wins))
map.world <- map_data('world') %>% 
  left_join(ch_count, by = "region") %>%
  mutate(wins = ifelse(is.na(wins), 0, wins),
         wins = factor(wins))
```

```{r}
ggplot(data=map.world, aes(x=long, y=lat)) +
  geom_polygon(colour = "black", aes(fill = wins, group = group)) +
  coord_cartesian(ylim=c(-55,68)) +
  scale_fill_manual(values = c("#d9d9d9", "#8c96c6", "#8c6bb1", "#88419d", "#810f7c", "#4d004b"), aesthetics = "fill") +
#  theme_void() + theme(legend.position = "bottom") +
  annotate("text", label = "FIFA men's champsionships by country", x = -100, y = 70, size = 8, colour = "#4d004b")
  
```

